services:
  calculation-client:
    image: lyazginad/calc:client
    networks:
      - calculation-net
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=calculation-server
    container_name: calculation-client
    labels:
      - "author=Daria Lyazgina"
      - "email=daria.lyazgina@gmail.com"
      - "maintainer=Daria Lyazgina"
    depends_on:
      - calculation-server

networks:
  calculation-net:
    driver: bridge